"""
SafeNet AI — Citizen Shield: Conversational Agent (v2)

Entry points:
  ask(query, language)                           → AgentResponse (single-turn)
  respond_to_user(user_message, history, language) → AgentResponse (multi-turn)

Design:
  Every response is generated by an LLM that receives:
    • The user's EXACT raw message text (never an intent label)
    • Grounding facts from Module A (pattern scores) and Module C (fraud graph)
    • The full conversation history so follow-ups build on prior context
    • Explicit instructions to reference specific details the user mentioned
      and to ask ONE clarifying question when the message is too vague

  Structured output (risk_level, next_steps) is extracted from the LLM's
  response via a lightweight post-processor and returned alongside the
  natural-language reply — the UI badge still gets what it needs.

  If no LLM key is available the agent falls back to a grounded template
  response (still uses the actual Module A/C data, no canned text).

Provider priority: GEMINI_API_KEY → OPENAI_API_KEY / LLM_API_KEY → template

Module contract (safenet.md §3):
  ask() / respond_to_user() are the plain Python functions.
  POST /shield/ask is a thin wrapper around ask().
"""

from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from typing import Optional

# ── Language support ───────────────────────────────────────────────────────────
SUPPORTED_LANGUAGES: dict[str, str] = {
    "en": "English",
    "hi": "Hindi",
    "ta": "Tamil",
    "te": "Telugu",
    "bn": "Bengali",
    "mr": "Marathi",
}

# ── Intent keyword table (still used for grounding signal selection) ───────────
_INTENT_RULES: list[tuple[str, list[str]]] = [
    ("counterfeit_note_query", [
        "fake note", "counterfeit", "fake currency", "fake rupee", "forged note",
        "note is fake", "currency note", "500 note", "2000 note", "old note",
        "suspicious note", "check note",
    ]),
    ("upi_fraud_check", [
        "upi", "gpay", "google pay", "phonepe", "paytm", "qr code",
        "collect request", "receive money", "bank transfer", "neft", "imps",
        "money transferred", "deducted", "account debited", "transaction",
        "paisa gaya", "paise", "rupee sent", "enter my upi", "upi pin", "scan and pay",
    ]),
    ("suspicious_call", [
        "call", "called me", "phone", "caller", "rang", "said they are", "arrest",
        "warrant", "cbi", "police", "customs", "microsoft", "anydesk",
        "teamviewer", "stay on the line", "don't tell", "do not tell", "spoofed",
        "threatening", "claiming to be", "aadhaar", "video call",
    ]),
]


def _classify_intent(text: str) -> str:
    lower = text.lower()
    for intent, kws in _INTENT_RULES:
        if any(kw in lower for kw in kws):
            return intent
    return "general_question"


# ── Grounding: gather Module A + C signals ────────────────────────────────────

def _gather_grounding(user_message: str, intent: str) -> dict:
    """
    Runs Module A and/or C on the user's raw message and returns structured
    grounding facts as a dict.  The LLM then WEAVES these into natural text —
    they are never pasted raw into the reply.
    """
    facts: dict = {
        "intent": intent,
        "pattern_score": None,
        "triggered_tactics": [],
        "kb_snippets": [],
        "blocklist_hit": None,
        "graph_case": None,
    }

    # ── Module A: scam pattern classifier ─────────────────────────────────────
    if intent in ("suspicious_call", "upi_fraud_check", "general_question"):
        try:
            from app.scam_detector.classifier import score_call, TACTIC_PATTERNS
            result = score_call(user_message, call_metadata={})
            facts["pattern_score"] = result["risk_score"]
            facts["triggered_tactics"] = result.get("triggered_patterns", [])
        except Exception:
            pass

    # ── Knowledge base ────────────────────────────────────────────────────────
    try:
        from app.citizen_shield.knowledge_base import search_knowledge_base, check_blocklist

        kb_hits = search_knowledge_base(user_message, top_k=2)
        facts["kb_snippets"] = [h["text"][:350] for h in kb_hits if h["similarity"] > 0.3]

        # Phone / UPI blocklist check
        phones = re.findall(r'[\+]?[\d\-\s]{10,15}', user_message)
        upi_ids = re.findall(r'[\w.\-]+@[\w.\-]+', user_message)
        for candidate in [p.strip() for p in phones] + upi_ids:
            hit = check_blocklist(candidate)
            if hit:
                facts["blocklist_hit"] = hit
                break
    except Exception:
        pass

    # ── Module C: fraud graph (only when a phone number is explicitly given) ──
    if intent in ("suspicious_call", "upi_fraud_check"):
        try:
            from app.number_checker.checker import check_number
            phones = re.findall(r'[\+]?[\d\-\s]{10,15}', user_message)
            if phones:
                nr = check_number(phones[0].strip(), pasted_text=user_message)
                if nr.risk_level in ("medium", "high", "critical") or nr.graph_case:
                    facts["graph_case"] = {
                        "risk_level": nr.risk_level,
                        "reasons": nr.reasons[:3],
                        "case_id": nr.graph_case.get("caseId") if nr.graph_case else None,
                    }
        except Exception:
            pass

    return facts


def _risk_level_from_facts(facts: dict) -> str:
    """Derives a risk_level string from grounding facts (used for badge display)."""
    score = facts.get("pattern_score") or 0
    tactics = facts.get("triggered_tactics", [])
    graph = facts.get("graph_case")
    blocklist = facts.get("blocklist_hit")

    if blocklist or (graph and graph["risk_level"] in ("high", "critical")):
        return "HIGH"
    if score >= 85 or (len(tactics) >= 3):
        return "HIGH"
    if score >= 40 or len(tactics) >= 1:
        return "MEDIUM"
    if facts["intent"] == "upi_fraud_check":
        return "MEDIUM"
    return "LOW"


# ── System prompt ─────────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """You are Citizen Shield, an advanced, highly intelligent AI fraud prevention assistant protecting Indian citizens.
Your role is to deeply analyze the user's situation, identify sophisticated scams, and provide realistic, highly effective guidance.

CRITICAL BEHAVIORAL RULES:
1. Act like a true, highly intelligent AI assistant (not a demo). Be empathetic, decisive, and exceptionally sharp.
2. ALWAYS weave specific details the user mentioned seamlessly into your response.
3. VARY your phrasing organically. Speak naturally, professionally, and directly.
4. If the message is incredibly brief (e.g., "help", "scam"), ask exactly ONE highly targeted clarifying question. Do not lecture prematurely.
5. CONVERSATION HISTORY: Seamlessly build on prior context. Do not repeat introductions.
7. DIRECT RESPONSE: You must respond directly to the user. If you perform any internal thinking, rule checks, drafting, or analysis, you MUST wrap that entire thinking process inside <think> and </think> tags so it can be filtered out. Never output plain-text draft steps or bulleted reasoning outside the <think> tags.

The grounding facts below are provided to give you real-time intelligence.
Weave them organically into your reasoning—do not quote them like a database dump."""


def _build_llm_prompt(
    user_message: str,
    facts: dict,
    history: list[dict],
) -> list[dict]:
    """
    Builds the messages list for the LLM call.
    history entries: {"role": "user"|"assistant", "content": str}
    """
    # Summarise grounding facts as an internal reference block (not shown to user)
    tactic_map = {
        "IMPERSONATION": "authority/government impersonation",
        "URGENCY_THREAT": "urgency and threat pressure ('immediately', 'legal action', 'account frozen')",
        "ISOLATION": "isolation instruction ('do not tell anyone', 'stay on the line')",
        "ACTION_REQUEST": "request to share OTP/password or install remote-access software",
        "SPOOFED_CALLER_ID": "spoofed caller ID",
        "VIDEO_COERCION": "video call / camera coercion",
        "GEMINI_VERIFIED": "AI-verified high scam likelihood",
    }

    grounding_lines = []

    score = facts.get("pattern_score")
    if score is not None:
        grounding_lines.append(f"Pattern match score: {score}/100")

    tactics = facts.get("triggered_tactics", [])
    if tactics:
        readable = [tactic_map.get(t, t.lower().replace("_", " ")) for t in tactics]
        grounding_lines.append(f"Detected scam tactics: {', '.join(readable)}")

    if facts.get("blocklist_hit"):
        bl = facts["blocklist_hit"]
        cnt = bl.get("report_count", "multiple")
        grounding_lines.append(
            f"Blocklist: a number/ID in this message has been reported {cnt} times "
            f"in our synthetic dataset for similar fraud. (SYNTHETIC DATA)"
        )

    if facts.get("graph_case"):
        gc = facts["graph_case"]
        grounding_lines.append(
            f"Fraud graph: a phone number in this message appears in our network "
            f"(Case {gc.get('case_id', 'N/A')}). Graph risk: {gc['risk_level']}. "
            f"Specific findings: {'; '.join(gc['reasons'][:2])}"
        )

    kb = facts.get("kb_snippets", [])
    if kb:
        grounding_lines.append(f"Relevant knowledge base context:\n  - {kb[0][:250]}")

    grounding_block = (
        "\n\n[GROUNDING FACTS — weave into response, do NOT quote verbatim]\n"
        + "\n".join(f"• {l}" for l in grounding_lines)
        if grounding_lines else ""
    )

    # Build messages
    messages = [{"role": "system", "content": _SYSTEM_PROMPT}]

    # Add conversation history (cap at last 6 turns to stay within token limits)
    for turn in history[-6:]:
        messages.append({"role": turn["role"], "content": turn["content"]})

    # Current user message with grounding appended (as system injection)
    user_content = user_message
    if grounding_block:
        user_content = user_message + grounding_block

    messages.append({"role": "user", "content": user_content})
    return messages


# ── LLM call (pluggable: Fireworks AI → Gemini → OpenAI → template fallback) ──

def _call_llm(messages: list[dict], task: str = "chat") -> Optional[str]:
    """
    Calls the best available LLM with automatic fallback chain.

    Priority: Fireworks AI (AMD Instinct GPUs) → Gemini → OpenAI → None

    For the Citizen Shield "chat" task, Fireworks routes to Gemma (Google DeepMind
    open model hosted on AMD hardware) — this satisfies the hackathon's
    "Best AMD-Hosted Gemma Project" bonus prize criterion.

    Args:
        messages: OpenAI-format messages list.
        task:     Logical task type for Fireworks model routing.

    Returns:
        Response text, or None if no LLM is available.
    """
    from app.fireworks_client import call_llm
    return call_llm(messages, task=task, temperature=0.7, max_tokens=600)


# ── Template fallback (grounded, not canned) ──────────────────────────────────

def _grounded_template_response(user_message: str, facts: dict) -> str:
    """
    Fallback when no LLM is available. Uses the actual grounding facts to
    compose a non-generic response. Still references what the user said.
    """
    tactics = facts.get("triggered_tactics", [])
    score = facts.get("pattern_score") or 0
    intent = facts.get("intent", "general_question")
    blocklist = facts.get("blocklist_hit")
    graph = facts.get("graph_case")

    tactic_map = {
        "IMPERSONATION": "authority impersonation (someone pretending to be an official or government body)",
        "URGENCY_THREAT": "urgency and threat pressure (forcing you to act immediately, threats of arrest or account freeze)",
        "ISOLATION": "isolation tactics (telling you not to tell anyone, keeping you on the line)",
        "ACTION_REQUEST": "requests to share OTPs or install software",
        "VIDEO_COERCION": "video call coercion",
    }

    # Trim user message for display
    user_snippet = user_message[:120].strip()

    parts = []

    if score >= 60 or len(tactics) >= 2:
        parts.append(
            f"I have analysed your situation carefully. The details you've shared—particularly \"{user_snippet}...\"—raise critical red flags. "
            "This is a known, highly sophisticated fraud pattern we are actively tracking."
        )
    elif score >= 30 or len(tactics) >= 1:
        parts.append(
            "I've reviewed your message. There are several concerning elements here that you need to be very cautious about."
        )
    elif intent == "counterfeit_note_query":
        parts.append("I understand you're concerned about a potentially counterfeit note. I can certainly help you verify this.")
    elif intent == "upi_fraud_check":
        parts.append("UPI fraud is currently one of the most prevalent threats. Let's look at this carefully to ensure your funds are safe.")
    else:
        parts.append(
            "I have processed your request. While I don't see an immediate, critical threat in this specific scenario, we should still proceed with caution."
        )

    if tactics:
        readable = [tactic_map.get(t, t.lower().replace("_", " ")) for t in tactics if t in tactic_map]
        if readable:
            parts.append(
                f"I detected clear psychological manipulation tactics in play here, specifically: {', '.join(readable)}. "
                "Scammers use these exact methods to bypass your logical thinking and force quick, emotional decisions."
            )

    if blocklist:
        cnt = blocklist.get("report_count", "multiple")
        parts.append(
            f"I also ran a background check on the identifiers you provided. My database shows this exact entity has been reported {cnt} times for similar fraudulent activity."
        )

    if graph:
        parts.append(
            f"Furthermore, network analysis (Case ID: {graph.get('case_id', 'N/A')}) links the phone number you mentioned directly to a known fraud ring, carrying a {graph['risk_level'].upper()} risk rating."
        )

    kb = facts.get("kb_snippets", [])
    if kb and len(parts) < 3:
        parts.append("Based on our latest intelligence: " + kb[0][:200] + "…")

    if not parts:
        parts.append(
            "I couldn't match this directly to our active threat feeds, but I strongly advise you to remain vigilant, especially if they are asking for money or personal details."
        )

    # Next steps
    risk = _risk_level_from_facts(facts)
    if risk == "HIGH":
        next_steps = (
            "Here is my immediate, critical advice:\n"
            "1. Disconnect entirely: Do not share any OTP, PIN, or personal info. Hang up right now.\n"
            "2. Block the contact: Prevent them from reaching you again.\n"
            "3. Report this incident: File an official complaint at cybercrime.gov.in or dial 1930 immediately.\n"
            "4. Inform someone: Tell a trusted family member what just happened."
        )
    elif risk == "MEDIUM":
        next_steps = (
            "Here is what you should do next:\n"
            "1. Pause all actions: Do not send money or share details until you verify their identity independently.\n"
            "2. Verify officially: Call your bank or the institution they claim to represent using a trusted, official phone number.\n"
            "3. Stay secure: If you feel pressured, disengage and report them to 1930."
        )
    else:
        next_steps = (
            "My recommended precautions:\n"
            "1. Trust your instincts: If anything feels slightly off, step back.\n"
            "2. Protect your credentials: Never share OTPs or passwords over a phone call, no matter who they claim to be.\n"
            "3. Stay informed: You can always report suspicious activity at cybercrime.gov.in."
        )

    # Check if any LLM API key is present in environment
    has_keys = bool(
        os.getenv("FIREWORKS_API_KEY") or 
        os.getenv("GEMINI_API_KEY") or 
        os.getenv("OPENAI_API_KEY") or 
        os.getenv("LLM_API_KEY")
    )
    
    alert = ""
    if not has_keys:
        alert = (
            "\n\n⚠️ **Deployment Alert**: SafeNet AI is currently running in offline fallback mode because no active LLM API keys "
            "(Fireworks AI, Gemini, or OpenAI) are configured in this environment. If this is deployed on Vercel, please add "
            "`FIREWORKS_API_KEY` to your Vercel Project Settings to enable live AMD GPU intelligence."
        )

    return "\n\n".join(parts) + "\n\n" + next_steps + alert


# ── Post-process: extract structured fields from LLM text ─────────────────────

def _extract_next_steps(llm_text: str) -> str:
    """Extracts the 'What you should do' section from LLM output if present."""
    patterns = [
        r"(?:What you should do|Next steps?|Steps?|Action items?|Recommended actions?)[\s:]*\n((?:\d+\..+\n?)+)",
        r"((?:\d+\.\s.+\n?){2,})",
    ]
    for pattern in patterns:
        m = re.search(pattern, llm_text, re.IGNORECASE)
        if m:
            return m.group(1).strip()
    return "Visit cybercrime.gov.in or call helpline 1930."


# ── Translate ─────────────────────────────────────────────────────────────────

def _translate(text: str, target_language: str) -> str:
    lang_name = SUPPORTED_LANGUAGES.get(target_language, target_language)
    translate_prompt = (
        f"Translate the following text into {lang_name}. "
        "Keep formatting (line breaks, bullet points) intact. "
        "Preserve proper nouns like 'SafeNet AI', 'cybercrime.gov.in', "
        "and phone numbers unchanged. Return ONLY the translated text.\n\n"
        f"{text}"
    )

    messages = [
        {
            "role": "system",
            "content": (
                f"You are a professional translator. "
                f"Translate into {lang_name}. Return ONLY the translated text."
            ),
        },
        {"role": "user", "content": translate_prompt},
    ]

    from app.fireworks_client import call_llm
    result = call_llm(messages, task="translation", temperature=0.1, max_tokens=1000)
    if result:
        return result

    return f"{text}\n\n[Translation to {lang_name} unavailable — no LLM provider configured.]"


# ── Public API ─────────────────────────────────────────────────────────────────

def respond_to_user(
    user_message: str,
    conversation_history: list[dict],
    language: str = "en",
) -> dict:
    """
    Multi-turn entry point. Every call passes:
      • The user's EXACT raw message (never just an intent label)
      • Full conversation history so follow-ups build on prior context
      • Grounding facts from Module A and C

    Args:
        user_message:          Raw text the user typed.
        conversation_history:  List of {"role": "user"|"assistant", "content": str}
                               from all prior turns in this session.
        language:              ISO 639-1 code (default "en").

    Returns:
        Chat widget-compatible dict:
        { id, sender, text, timestamp, isActionable, intent, risk_level, language,
          next_steps }
    """
    intent = _classify_intent(user_message)
    facts = _gather_grounding(user_message, intent)
    risk_level = _risk_level_from_facts(facts)

    # Build LLM messages with history
    messages = _build_llm_prompt(user_message, facts, conversation_history)
    llm_text = _call_llm(messages, task="chat")

    if llm_text:
        text_en = llm_text
    else:
        text_en = _grounded_template_response(user_message, facts)

    next_steps = _extract_next_steps(text_en)

    # Translate if needed
    if language != "en" and language in SUPPORTED_LANGUAGES:
        text_final = _translate(text_en, language)
    else:
        text_final = text_en

    return {
        "id": f"cs-{abs(hash(user_message + str(datetime.now(timezone.utc).timestamp()))) % 10**9:09d}",
        "sender": "bot",
        "text": text_final,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "isActionable": risk_level in ("HIGH", "MEDIUM"),
        "intent": intent,
        "risk_level": risk_level,
        "language": language,
        "next_steps": next_steps,
    }


def ask(query: str, language: str = "en") -> dict:
    """
    Single-turn wrapper for backward compatibility with the /shield/ask endpoint.
    Calls respond_to_user with no history.
    """
    return respond_to_user(
        user_message=query,
        conversation_history=[],
        language=language,
    )
