"""
SafeNet AI — Citizen Shield: Conversational Agent (v2)

Entry points:
  ask(query, language)                           → AgentResponse (single-turn)
  respond_to_user(user_message, history, language) → AgentResponse (multi-turn)

Design:
  Every response is generated by an LLM that receives:
    • The user's EXACT raw message text (never an intent label)
    • Grounding facts from Module A (pattern scores) and Module C (fraud graph)
    • The full conversation history so follow-ups build on prior context
    • Explicit instructions to reference specific details the user mentioned
      and to ask ONE clarifying question when the message is too vague

  Structured output (risk_level, next_steps) is extracted from the LLM's
  response via a lightweight post-processor and returned alongside the
  natural-language reply — the UI badge still gets what it needs.

  If no LLM key is available the agent falls back to a grounded template
  response (still uses the actual Module A/C data, no canned text).

Provider priority: GEMINI_API_KEY → OPENAI_API_KEY / LLM_API_KEY → template

Module contract (safenet.md §3):
  ask() / respond_to_user() are the plain Python functions.
  POST /shield/ask is a thin wrapper around ask().
"""

from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from typing import Optional

# ── Language support ───────────────────────────────────────────────────────────
SUPPORTED_LANGUAGES: dict[str, str] = {
    "en": "English",
    "hi": "Hindi",
    "ta": "Tamil",
    "te": "Telugu",
    "bn": "Bengali",
    "mr": "Marathi",
}

# ── Intent keyword table (still used for grounding signal selection) ───────────
_INTENT_RULES: list[tuple[str, list[str]]] = [
    ("counterfeit_note_query", [
        "fake note", "counterfeit", "fake currency", "fake rupee", "forged note",
        "note is fake", "currency note", "500 note", "2000 note", "old note",
        "suspicious note", "check note",
    ]),
    ("upi_fraud_check", [
        "upi", "gpay", "google pay", "phonepe", "paytm", "qr code",
        "collect request", "receive money", "bank transfer", "neft", "imps",
        "money transferred", "deducted", "account debited", "transaction",
        "paisa gaya", "paise", "rupee sent", "enter my upi", "upi pin", "scan and pay",
    ]),
    ("suspicious_call", [
        "call", "called me", "phone", "caller", "rang", "said they are", "arrest",
        "warrant", "cbi", "police", "customs", "microsoft", "anydesk",
        "teamviewer", "stay on the line", "don't tell", "do not tell", "spoofed",
        "threatening", "claiming to be", "aadhaar", "video call",
    ]),
]


def _classify_intent(text: str) -> str:
    lower = text.lower()
    for intent, kws in _INTENT_RULES:
        if any(kw in lower for kw in kws):
            return intent
    return "general_question"


# ── Grounding: gather Module A + C signals ────────────────────────────────────

def _gather_grounding(user_message: str, intent: str) -> dict:
    """
    Runs Module A and/or C on the user's raw message and returns structured
    grounding facts as a dict.  The LLM then WEAVES these into natural text —
    they are never pasted raw into the reply.
    """
    facts: dict = {
        "intent": intent,
        "pattern_score": None,
        "triggered_tactics": [],
        "kb_snippets": [],
        "blocklist_hit": None,
        "graph_case": None,
    }

    # ── Module A: scam pattern classifier ─────────────────────────────────────
    if intent in ("suspicious_call", "upi_fraud_check", "general_question"):
        try:
            from app.scam_detector.classifier import score_call, TACTIC_PATTERNS
            result = score_call(user_message, call_metadata={})
            facts["pattern_score"] = result["risk_score"]
            facts["triggered_tactics"] = result.get("triggered_patterns", [])
        except Exception:
            pass

    # ── Knowledge base ────────────────────────────────────────────────────────
    try:
        from app.citizen_shield.knowledge_base import search_knowledge_base, check_blocklist

        kb_hits = search_knowledge_base(user_message, top_k=2)
        facts["kb_snippets"] = [h["text"][:350] for h in kb_hits if h["similarity"] > 0.3]

        # Phone / UPI blocklist check
        phones = re.findall(r'[\+]?[\d\-\s]{10,15}', user_message)
        upi_ids = re.findall(r'[\w.\-]+@[\w.\-]+', user_message)
        for candidate in [p.strip() for p in phones] + upi_ids:
            hit = check_blocklist(candidate)
            if hit:
                facts["blocklist_hit"] = hit
                break
    except Exception:
        pass

    # ── Module C: fraud graph (only when a phone number is explicitly given) ──
    if intent in ("suspicious_call", "upi_fraud_check"):
        try:
            from app.number_checker.checker import check_number
            phones = re.findall(r'[\+]?[\d\-\s]{10,15}', user_message)
            if phones:
                nr = check_number(phones[0].strip(), pasted_text=user_message)
                if nr.risk_level in ("medium", "high", "critical") or nr.graph_case:
                    facts["graph_case"] = {
                        "risk_level": nr.risk_level,
                        "reasons": nr.reasons[:3],
                        "case_id": nr.graph_case.get("caseId") if nr.graph_case else None,
                    }
        except Exception:
            pass

    return facts


def _risk_level_from_facts(facts: dict) -> str:
    """Derives a risk_level string from grounding facts (used for badge display)."""
    score = facts.get("pattern_score") or 0
    tactics = facts.get("triggered_tactics", [])
    graph = facts.get("graph_case")
    blocklist = facts.get("blocklist_hit")

    if blocklist or (graph and graph["risk_level"] in ("high", "critical")):
        return "HIGH"
    if score >= 85 or (len(tactics) >= 3):
        return "HIGH"
    if score >= 40 or len(tactics) >= 1:
        return "MEDIUM"
    if facts["intent"] == "upi_fraud_check":
        return "MEDIUM"
    return "LOW"


# ── System prompt ─────────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """You are Citizen Shield, SafeNet AI's fraud prevention assistant for Indian citizens.
Your role is to help people understand if they are being scammed and what to do about it.

CRITICAL RULES (follow every single one):
1. ALWAYS reference specific details the user actually mentioned.
   - If they said "someone claiming to be from CBI asked for my Aadhaar" → say "the CBI impersonation call" and "the Aadhaar request" explicitly.
   - If they mentioned a video call, a specific amount, an app name, or a location → weave it into your response.
   - NEVER give a generic answer that ignores what they described.

2. NEVER paste raw data as your reply.
   - Do not show "risk_score: 78" or "triggered_patterns: [IMPERSONATION]".
   - Instead, say things like: "what you described — the part about being asked to stay on a video call while they processed your 'case' — is a classic isolation tactic we've flagged in dozens of similar reports."

3. VARY your phrasing naturally every response.
   - Do not start every reply with "Thank you for reaching out" or the same opener.
   - Write the way a knowledgeable, empathetic person would — someone who actually read what the user wrote.

4. If the message is SHORT or VAGUE (less than 15 words, no specific details):
   - Ask ONE specific clarifying question to understand the situation better.
   - Do NOT give a generic fraud lecture. Wait for the answer.
   - Example: "Could you tell me a bit more — did they call you, send a message, or was it something online?"

5. CONVERSATION HISTORY: If there is prior conversation, BUILD on it.
   - Reference what you already discussed. Do not restart from scratch.
   - If the user provides new details, update your assessment.

6. Keep responses conversational, 3–6 sentences max for the main reply,
   then a brief "What you should do:" section (2–4 specific action items).

7. End with one line: "SafeNet AI · Demo system · Not legal advice"

The grounding facts below are provided to help you give accurate advice.
Weave them naturally into your response — do not quote them verbatim."""


def _build_llm_prompt(
    user_message: str,
    facts: dict,
    history: list[dict],
) -> list[dict]:
    """
    Builds the messages list for the LLM call.
    history entries: {"role": "user"|"assistant", "content": str}
    """
    # Summarise grounding facts as an internal reference block (not shown to user)
    tactic_map = {
        "IMPERSONATION": "authority/government impersonation",
        "URGENCY_THREAT": "urgency and threat pressure ('immediately', 'legal action', 'account frozen')",
        "ISOLATION": "isolation instruction ('do not tell anyone', 'stay on the line')",
        "ACTION_REQUEST": "request to share OTP/password or install remote-access software",
        "SPOOFED_CALLER_ID": "spoofed caller ID",
        "VIDEO_COERCION": "video call / camera coercion",
        "GEMINI_VERIFIED": "AI-verified high scam likelihood",
    }

    grounding_lines = []

    score = facts.get("pattern_score")
    if score is not None:
        grounding_lines.append(f"Pattern match score: {score}/100")

    tactics = facts.get("triggered_tactics", [])
    if tactics:
        readable = [tactic_map.get(t, t.lower().replace("_", " ")) for t in tactics]
        grounding_lines.append(f"Detected scam tactics: {', '.join(readable)}")

    if facts.get("blocklist_hit"):
        bl = facts["blocklist_hit"]
        cnt = bl.get("report_count", "multiple")
        grounding_lines.append(
            f"Blocklist: a number/ID in this message has been reported {cnt} times "
            f"in our synthetic dataset for similar fraud. (SYNTHETIC DATA)"
        )

    if facts.get("graph_case"):
        gc = facts["graph_case"]
        grounding_lines.append(
            f"Fraud graph: a phone number in this message appears in our network "
            f"(Case {gc.get('case_id', 'N/A')}). Graph risk: {gc['risk_level']}. "
            f"Specific findings: {'; '.join(gc['reasons'][:2])}"
        )

    kb = facts.get("kb_snippets", [])
    if kb:
        grounding_lines.append(f"Relevant knowledge base context:\n  - {kb[0][:250]}")

    grounding_block = (
        "\n\n[GROUNDING FACTS — weave into response, do NOT quote verbatim]\n"
        + "\n".join(f"• {l}" for l in grounding_lines)
        if grounding_lines else ""
    )

    # Build messages
    messages = [{"role": "system", "content": _SYSTEM_PROMPT}]

    # Add conversation history (cap at last 6 turns to stay within token limits)
    for turn in history[-6:]:
        messages.append({"role": turn["role"], "content": turn["content"]})

    # Current user message with grounding appended (as system injection)
    user_content = user_message
    if grounding_block:
        user_content = user_message + grounding_block

    messages.append({"role": "user", "content": user_content})
    return messages


# ── LLM call (pluggable: Gemini → OpenAI → template fallback) ─────────────────

def _call_llm(messages: list[dict]) -> Optional[str]:
    """
    Calls an LLM with the given messages list.
    Returns the response text, or None if no LLM is available.
    """
    # ── Gemini ────────────────────────────────────────────────────────────────
    gemini_key = os.getenv("GEMINI_API_KEY")
    if gemini_key:
        try:
            from google import genai
            from google.genai import types as genai_types

            client = genai.Client(api_key=gemini_key)

            # Gemini expects a flat contents string; prefix system + history
            system_msg = next((m["content"] for m in messages if m["role"] == "system"), "")
            conversation_parts = []
            for m in messages:
                if m["role"] == "system":
                    continue
                prefix = "User: " if m["role"] == "user" else "Citizen Shield: "
                conversation_parts.append(f"{prefix}{m['content']}")

            full_prompt = system_msg + "\n\n" + "\n\n".join(conversation_parts)

            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=full_prompt,
                config=genai_types.GenerateContentConfig(
                    temperature=0.7,
                    max_output_tokens=600,
                ),
            )
            return response.text.strip()
        except Exception as e:
            print(f"[citizen_shield] Gemini call failed: {e}")

    # ── OpenAI ────────────────────────────────────────────────────────────────
    openai_key = os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY")
    if openai_key:
        try:
            from openai import OpenAI
            client = OpenAI(api_key=openai_key)
            resp = client.chat.completions.create(
                model=os.getenv("OPENAI_MODEL", "gpt-4o"),
                messages=messages,
                max_tokens=600,
                temperature=0.7,
            )
            return resp.choices[0].message.content.strip()
        except Exception as e:
            print(f"[citizen_shield] OpenAI call failed: {e}")

    return None


# ── Template fallback (grounded, not canned) ──────────────────────────────────

def _grounded_template_response(user_message: str, facts: dict) -> str:
    """
    Fallback when no LLM is available. Uses the actual grounding facts to
    compose a non-generic response. Still references what the user said.
    """
    tactics = facts.get("triggered_tactics", [])
    score = facts.get("pattern_score") or 0
    intent = facts.get("intent", "general_question")
    blocklist = facts.get("blocklist_hit")
    graph = facts.get("graph_case")

    tactic_map = {
        "IMPERSONATION": "authority impersonation (someone pretending to be an official or government body)",
        "URGENCY_THREAT": "urgency and threat pressure (forcing you to act immediately, threats of arrest or account freeze)",
        "ISOLATION": "isolation tactics (telling you not to tell anyone, keeping you on the line)",
        "ACTION_REQUEST": "requests to share OTPs or install software",
        "VIDEO_COERCION": "video call coercion",
    }

    # Trim user message for display
    user_snippet = user_message[:120].strip()

    parts = []

    if score >= 60 or len(tactics) >= 2:
        parts.append(
            f"Based on what you described — \"{user_snippet}...\" — this looks like "
            f"a high-risk scam situation."
        )
    elif score >= 30 or len(tactics) >= 1:
        parts.append(
            f"What you described raises some warning flags that are worth taking seriously."
        )
    elif intent == "counterfeit_note_query":
        parts.append("Here is what to do if you think you have received a counterfeit note.")
    elif intent == "upi_fraud_check":
        parts.append("UPI fraud is one of the most common scam types right now. Let me help you check this.")
    else:
        parts.append(
            "I don't have a specific record matching this, but I can share what to watch for."
        )

    if tactics:
        readable = [tactic_map.get(t, t.lower().replace("_", " ")) for t in tactics if t in tactic_map]
        if readable:
            parts.append(
                f"Specifically, your message contains language patterns associated with: "
                f"{', '.join(readable)}."
            )

    if blocklist:
        cnt = blocklist.get("report_count", "multiple")
        parts.append(
            f"A number or ID in your message has been reported {cnt} times in our "
            f"system for similar fraud. (⚠️ Synthetic data — demo only)"
        )

    if graph:
        parts.append(
            f"A phone number you mentioned appears in our fraud network records "
            f"(Case {graph.get('case_id', 'N/A')}) with a {graph['risk_level']} risk rating."
        )

    kb = facts.get("kb_snippets", [])
    if kb and len(parts) < 3:
        parts.append(kb[0][:200] + "…")

    if not parts:
        parts.append(
            "I wasn't able to find a specific match in our records, but it's always wise to "
            "be cautious about unsolicited calls or messages asking for personal information."
        )

    # Next steps
    risk = _risk_level_from_facts(facts)
    if risk == "HIGH":
        next_steps = (
            "What you should do:\n"
            "1. Do not share any OTP, PIN, or personal information — hang up immediately.\n"
            "2. Block the number and do not call back.\n"
            "3. Report at cybercrime.gov.in or call helpline 1930.\n"
            "4. Tell a trusted family member about this now."
        )
    elif risk == "MEDIUM":
        next_steps = (
            "What you should do:\n"
            "1. Do not take any action they requested until you verify independently.\n"
            "2. Call your bank or the relevant government body's official number.\n"
            "3. If uncertain, report at cybercrime.gov.in or call 1930."
        )
    else:
        next_steps = (
            "What you should do:\n"
            "1. Trust your instincts — if something felt off, it may be.\n"
            "2. Never share OTPs or passwords with anyone who called you.\n"
            "3. Report suspicious contact at cybercrime.gov.in."
        )

    return "\n\n".join(parts) + "\n\n" + next_steps + "\n\nSafeNet AI · Demo system · Not legal advice"


# ── Post-process: extract structured fields from LLM text ─────────────────────

def _extract_next_steps(llm_text: str) -> str:
    """Extracts the 'What you should do' section from LLM output if present."""
    patterns = [
        r"(?:What you should do|Next steps?|Steps?|Action items?|Recommended actions?)[\s:]*\n((?:\d+\..+\n?)+)",
        r"((?:\d+\.\s.+\n?){2,})",
    ]
    for pattern in patterns:
        m = re.search(pattern, llm_text, re.IGNORECASE)
        if m:
            return m.group(1).strip()
    return "Visit cybercrime.gov.in or call helpline 1930."


# ── Translate ─────────────────────────────────────────────────────────────────

def _translate(text: str, target_language: str) -> str:
    lang_name = SUPPORTED_LANGUAGES.get(target_language, target_language)
    translate_prompt = (
        f"Translate the following text into {lang_name}. "
        "Keep formatting (line breaks, bullet points) intact. "
        "Preserve proper nouns like 'SafeNet AI', 'cybercrime.gov.in', "
        "and phone numbers unchanged. Return ONLY the translated text.\n\n"
        f"{text}"
    )

    gemini_key = os.getenv("GEMINI_API_KEY")
    if gemini_key:
        try:
            from google import genai
            from google.genai import types as genai_types
            client = genai.Client(api_key=gemini_key)
            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=translate_prompt,
                config=genai_types.GenerateContentConfig(temperature=0.1, max_output_tokens=1000),
            )
            return response.text.strip()
        except Exception:
            pass

    openai_key = os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY")
    if openai_key:
        try:
            from openai import OpenAI
            client = OpenAI(api_key=openai_key)
            resp = client.chat.completions.create(
                model=os.getenv("OPENAI_MODEL", "gpt-4o"),
                messages=[
                    {"role": "system", "content": f"You are a translator. Translate into {lang_name}. Return ONLY the translated text."},
                    {"role": "user", "content": text},
                ],
                max_tokens=1000, temperature=0.1,
            )
            return resp.choices[0].message.content.strip()
        except Exception as e:
            return f"{text}\n\n[Translation to {lang_name} failed. Shown in English.]"

    return f"{text}\n\n[Translation to {lang_name} unavailable — GEMINI_API_KEY not set.]"


# ── Public API ─────────────────────────────────────────────────────────────────

def respond_to_user(
    user_message: str,
    conversation_history: list[dict],
    language: str = "en",
) -> dict:
    """
    Multi-turn entry point. Every call passes:
      • The user's EXACT raw message (never just an intent label)
      • Full conversation history so follow-ups build on prior context
      • Grounding facts from Module A and C

    Args:
        user_message:          Raw text the user typed.
        conversation_history:  List of {"role": "user"|"assistant", "content": str}
                               from all prior turns in this session.
        language:              ISO 639-1 code (default "en").

    Returns:
        Chat widget-compatible dict:
        { id, sender, text, timestamp, isActionable, intent, risk_level, language,
          next_steps }
    """
    intent = _classify_intent(user_message)
    facts = _gather_grounding(user_message, intent)
    risk_level = _risk_level_from_facts(facts)

    # Build LLM messages with history
    messages = _build_llm_prompt(user_message, facts, conversation_history)
    llm_text = _call_llm(messages)

    if llm_text:
        text_en = llm_text
    else:
        text_en = _grounded_template_response(user_message, facts)

    next_steps = _extract_next_steps(text_en)

    # Translate if needed
    if language != "en" and language in SUPPORTED_LANGUAGES:
        text_final = _translate(text_en, language)
    else:
        text_final = text_en

    return {
        "id": f"cs-{abs(hash(user_message + str(datetime.now(timezone.utc).timestamp()))) % 10**9:09d}",
        "sender": "bot",
        "text": text_final,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "isActionable": risk_level in ("HIGH", "MEDIUM"),
        "intent": intent,
        "risk_level": risk_level,
        "language": language,
        "next_steps": next_steps,
    }


def ask(query: str, language: str = "en") -> dict:
    """
    Single-turn wrapper for backward compatibility with the /shield/ask endpoint.
    Calls respond_to_user with no history.
    """
    return respond_to_user(
        user_message=query,
        conversation_history=[],
        language=language,
    )
